//! Re-export metadata types for Dec32 shapes.
//!
//! These are generated by the `define_primitive_shape!` macro in `fixed_shape.rs`.

pub use super::dec32_shape::{Dec32Meta, Dec32MetaDyn, Dec32MetaStatic};
