//! Re-export metadata types for Fixed shapes.
//!
//! These are generated by the `define_primitive_shape!` macro in `fixed_shape.rs`.

pub use super::fixed_shape::{FixedMeta, FixedMetaDyn, FixedMetaStatic};
