//! Re-export metadata types for Bool shapes.
//!
//! These are generated by the `define_primitive_shape!` macro in `bool_shape.rs`.

pub use super::bool_shape::{BoolMeta, BoolMetaDyn, BoolMetaStatic};
