//! Re-export metadata types for Vec4 shapes.
//!
//! These are generated by the `define_primitive_shape!` macro in `vec4_shape.rs`.

pub use super::vec4_shape::{Vec4Meta, Vec4MetaDyn, Vec4MetaStatic};
