//! Re-export metadata types for Vec3 shapes.
//!
//! These are generated by the `define_primitive_shape!` macro in `vec3_shape.rs`.

pub use super::vec3_shape::{Vec3Meta, Vec3MetaDyn, Vec3MetaStatic};
