//! Re-export metadata types for Vec2 shapes.
//!
//! These are generated by the `define_primitive_shape!` macro in `vec2_shape.rs`.

pub use super::vec2_shape::{Vec2Meta, Vec2MetaDyn, Vec2MetaStatic};
