//! Re-export metadata types for Mat3 shapes.
//!
//! These are generated by the `define_primitive_shape!` macro in `mat3_shape.rs`.

pub use super::mat3_shape::{Mat3Meta, Mat3MetaDyn, Mat3MetaStatic};
