//! Re-export metadata types for Int32 shapes.
//!
//! These are generated by the `define_primitive_shape!` macro in `int32_shape.rs`.

pub use super::int32_shape::{Int32Meta, Int32MetaDyn, Int32MetaStatic};
